-- ═══════════════════════════════════════════════════════════════════
-- Soul Gold — Full automated setup (idempotent, safe to re-run)
-- Executed by: npm run setup:supabase
-- ═══════════════════════════════════════════════════════════════════

-- ── Orders (checkout) ──────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.orders (
  id               UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  customer_name    TEXT NOT NULL,
  customer_phone   TEXT NOT NULL,
  customer_address TEXT NOT NULL,
  items            JSONB NOT NULL,
  total_price      NUMERIC(10,2) NOT NULL CHECK (total_price >= 0),
  created_at       TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "orders_public_insert" ON public.orders;
CREATE POLICY "orders_public_insert"
  ON public.orders FOR INSERT
  WITH CHECK (true);

-- ── Products v2 (Shopify-style catalog) ────────────────────────────
-- Drop legacy v1 schema (no sku column) so v2 can be created cleanly
DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public' AND table_name = 'products' AND column_name = 'category'
  ) AND NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public' AND table_name = 'products' AND column_name = 'sku'
  ) THEN
    DROP TABLE public.products CASCADE;
  END IF;
END $$;

CREATE TABLE IF NOT EXISTS public.products (
  id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sku              TEXT NOT NULL UNIQUE,
  name_en          TEXT NOT NULL,
  name_ar          TEXT NOT NULL,
  description_en   TEXT,
  description_ar   TEXT,
  sub_en           TEXT,
  sub_ar           TEXT,
  price            NUMERIC(10,2) NOT NULL CHECK (price >= 0),
  category_en      TEXT NOT NULL,
  category_ar      TEXT NOT NULL,
  image_url        TEXT NOT NULL,
  image_file       TEXT,
  stock_quantity   INTEGER NOT NULL DEFAULT 0 CHECK (stock_quantity >= 0),
  is_featured      BOOLEAN NOT NULL DEFAULT false,
  badge_en         TEXT,
  badge_ar         TEXT,
  bg_color         TEXT NOT NULL DEFAULT 'bg-cream',
  created_at       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at       TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE OR REPLACE FUNCTION public.set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS products_updated_at ON public.products;
CREATE TRIGGER products_updated_at
  BEFORE UPDATE ON public.products
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "products_public_read" ON public.products;
CREATE POLICY "products_public_read"
  ON public.products FOR SELECT
  USING (true);

CREATE INDEX IF NOT EXISTS products_category_en_idx ON public.products (category_en);
CREATE INDEX IF NOT EXISTS products_is_featured_idx ON public.products (is_featured);
CREATE INDEX IF NOT EXISTS products_sku_idx ON public.products (sku);

-- ── Storage buckets ────────────────────────────────────────────────
INSERT INTO storage.buckets (id, name, public)
VALUES ('product-images', 'product-images', true)
ON CONFLICT (id) DO UPDATE SET public = true;

INSERT INTO storage.buckets (id, name, public)
VALUES ('brand-assets', 'brand-assets', true)
ON CONFLICT (id) DO UPDATE SET public = true;

-- product-images policies
DROP POLICY IF EXISTS "product_images_public_read" ON storage.objects;
CREATE POLICY "product_images_public_read"
  ON storage.objects FOR SELECT
  USING (bucket_id = 'product-images');

DROP POLICY IF EXISTS "product_images_service_upload" ON storage.objects;
CREATE POLICY "product_images_service_upload"
  ON storage.objects FOR INSERT
  WITH CHECK (bucket_id = 'product-images');

DROP POLICY IF EXISTS "product_images_service_update" ON storage.objects;
CREATE POLICY "product_images_service_update"
  ON storage.objects FOR UPDATE
  USING (bucket_id = 'product-images');

DROP POLICY IF EXISTS "product_images_service_delete" ON storage.objects;
CREATE POLICY "product_images_service_delete"
  ON storage.objects FOR DELETE
  USING (bucket_id = 'product-images');

-- brand-assets policies
DROP POLICY IF EXISTS "brand_assets_public_read" ON storage.objects;
CREATE POLICY "brand_assets_public_read"
  ON storage.objects FOR SELECT
  USING (bucket_id = 'brand-assets');

DROP POLICY IF EXISTS "brand_assets_service_upload" ON storage.objects;
CREATE POLICY "brand_assets_service_upload"
  ON storage.objects FOR INSERT
  WITH CHECK (bucket_id = 'brand-assets');

DROP POLICY IF EXISTS "brand_assets_service_update" ON storage.objects;
CREATE POLICY "brand_assets_service_update"
  ON storage.objects FOR UPDATE
  USING (bucket_id = 'brand-assets');

DROP POLICY IF EXISTS "brand_assets_service_delete" ON storage.objects;
CREATE POLICY "brand_assets_service_delete"
  ON storage.objects FOR DELETE
  USING (bucket_id = 'brand-assets');


-- ── Seed all 20 products ───────────────────────────────────────────
INSERT INTO public.products (
  sku, name_en, name_ar, description_en, description_ar,
  sub_en, sub_ar, price, category_en, category_ar,
  image_url, image_file, stock_quantity, is_featured
) VALUES
  ('peas-pouch', 'Frozen Green Peas', 'بازلاء خضراء مجمدة', 'Perfectly frozen green peas in a premium pouch.', 'بازلاء خضراء مجمدة بشكل مثالي في كيس فاخر.', 'Pouch · Perfectly Frozen', 'كيس · مجمدة مثالياً', 15, 'Frozen', 'مجمدات', 'https://otuewefcsusojkjfgadv.supabase.co/storage/v1/object/public/product-images/catalog/WhatsApp%20Image%202026-06-14%20at%2010.19.34%20AM%20(1).jpeg', 'WhatsApp Image 2026-06-14 at 10.19.34 AM (1).jpeg', 120, false),
  ('strawberry', 'Frozen Strawberries', 'فراولة مجمدة', 'Deep-frozen strawberries for smoothies and desserts.', 'فراولة مجمدة عميقاً للعصائر والحلويات.', '400g · Deep Frozen', '٤٠٠ج · مجمدة عميقاً', 18, 'Frozen', 'مجمدات', 'https://otuewefcsusojkjfgadv.supabase.co/storage/v1/object/public/product-images/catalog/WhatsApp%20Image%202026-06-14%20at%2010.19.34%20AM%20(2).jpeg', 'WhatsApp Image 2026-06-14 at 10.19.34 AM (2).jpeg', 90, false),
  ('garlic-mayo', 'Garlic Mayonnaise', 'مايونيز بالثوم', 'Rich, creamy artisanal garlic mayonnaise.', 'مايونيز بالثوم كريمي وحرفي الصنع.', 'Rich · Creamy · Artisanal', 'كريمي · حرفي الصنع', 22, 'Sauces', 'صلصات', 'https://otuewefcsusojkjfgadv.supabase.co/storage/v1/object/public/product-images/catalog/WhatsApp%20Image%202026-06-14%20at%2010.19.34%20AM%20(3).jpeg', 'WhatsApp Image 2026-06-14 at 10.19.34 AM (3).jpeg', 80, false),
  ('chicken-fresh', 'Fresh Whole Chicken', 'دجاجة كاملة طازجة', 'Fresh whole chicken, farm-sourced daily.', 'دجاجة كاملة طازجة من المزارع يومياً.', '800g ± 50g · Fresh', '٨٠٠ج ± ٥٠ج · طازج', 32, 'Poultry', 'دواجن', 'https://otuewefcsusojkjfgadv.supabase.co/storage/v1/object/public/product-images/catalog/WhatsApp%20Image%202026-06-14%20at%2010.19.35%20AM.jpeg', 'WhatsApp Image 2026-06-14 at 10.19.35 AM.jpeg', 60, false),
  ('fries-dark', 'Golden French Fries', 'بطاطس مقلية ذهبية', 'Premium-cut frozen french fries.', 'بطاطس مقلية مجمدة بقطع ممتازة.', 'Premium Cut · Frozen', 'قطع ممتازة · مجمدة', 20, 'Frozen', 'مجمدات', 'https://otuewefcsusojkjfgadv.supabase.co/storage/v1/object/public/product-images/catalog/WhatsApp%20Image%202026-06-14%20at%2010.19.36%20AM%20(1).jpeg', 'WhatsApp Image 2026-06-14 at 10.19.36 AM (1).jpeg', 100, false),
  ('peas-bag', 'Green Peas Premium Bag', 'بازلاء خضراء فاخرة', 'Premium frozen green peas in a family bag.', 'بازلاء خضراء مجمدة فاخرة في كيس عائلي.', '400g · Premium', '٤٠٠ج · فاخر', 14, 'Frozen', 'مجمدات', 'https://otuewefcsusojkjfgadv.supabase.co/storage/v1/object/public/product-images/catalog/WhatsApp%20Image%202026-06-14%20at%2010.19.36%20AM%20(3).jpeg', 'WhatsApp Image 2026-06-14 at 10.19.36 AM (3).jpeg', 110, false),
  ('cream', 'Natural Fresh Cream', 'قشطة طبيعية', '100% natural fresh cream for cooking and desserts.', 'قشطة طبيعية ١٠٠٪ للطبخ والحلويات.', '900g · 100% Natural', '٩٠٠ج · طبيعي ١٠٠٪', 28, 'Dairy', 'ألبان', 'https://otuewefcsusojkjfgadv.supabase.co/storage/v1/object/public/product-images/catalog/WhatsApp%20Image%202026-06-14%20at%2010.19.37%20AM.jpeg', 'WhatsApp Image 2026-06-14 at 10.19.37 AM.jpeg', 70, false),
  ('ketchup-sachets', 'Tomato Ketchup Sachets', 'كاتشب طماطم أكياس', 'Box of 100 tomato ketchup sachets.', 'كرتون ١٠٠ كيس كاتشب طماطم.', 'Box of 100 Sachets', 'كرتون ١٠٠ كيس', 25, 'Sauces', 'صلصات', 'https://otuewefcsusojkjfgadv.supabase.co/storage/v1/object/public/product-images/catalog/WhatsApp%20Image%202026-06-14%20at%2010.19.37%20AM%20(1).jpeg', 'WhatsApp Image 2026-06-14 at 10.19.37 AM (1).jpeg', 50, false),
  ('peas-can', 'Green Peas Premium Can', 'بازلاء معلبة فاخرة', 'Premium canned green peas.', 'بازلاء خضراء معلبة فاخرة.', '400g · Premium Can', '٤٠٠ج · علبة فاخرة', 14, 'Canned', 'معلبات', 'https://otuewefcsusojkjfgadv.supabase.co/storage/v1/object/public/product-images/catalog/WhatsApp%20Image%202026-06-14%20at%2010.19.38%20AM%20(2).jpeg', 'WhatsApp Image 2026-06-14 at 10.19.38 AM (2).jpeg', 85, false),
  ('sunflower-oil', 'Pure Sunflower Oil', 'زيت دوار الشمس الصافي', '100% pure natural sunflower oil.', 'زيت دوار الشمس صافي ١٠٠٪.', '100% Pure · Natural', 'صافي ١٠٠٪ · طبيعي', 35, 'Oils', 'زيوت', 'https://otuewefcsusojkjfgadv.supabase.co/storage/v1/object/public/product-images/catalog/WhatsApp%20Image%202026-06-14%20at%2010.19.39%20AM%20(1).jpeg', 'WhatsApp Image 2026-06-14 at 10.19.39 AM (1).jpeg', 75, false),
  ('fries-alzahabia', 'Alzahabia French Fries', 'بطاطس الذهبية', 'Premium quality crispy frozen fries.', 'بطاطس مقلية مجمدة فائقة الجودة.', 'Premium Quality · Crispy', 'جودة فائقة · مقرمشة', 20, 'Frozen', 'مجمدات', 'https://otuewefcsusojkjfgadv.supabase.co/storage/v1/object/public/product-images/catalog/WhatsApp%20Image%202026-06-14%20at%2010.19.39%20AM%20(2).jpeg', 'WhatsApp Image 2026-06-14 at 10.19.39 AM (2).jpeg', 95, false),
  ('chicken-fresh-2', 'Fresh Chicken — Premium', 'دجاج طازج فريش', 'Saudi-made premium fresh chicken.', 'دجاج طازج فاخر صناعة سعودية.', '800g ± 50g · Saudi Made', '٨٠٠ج ± ٥٠ج · صناعة سعودية', 32, 'Poultry', 'دواجن', 'https://otuewefcsusojkjfgadv.supabase.co/storage/v1/object/public/product-images/catalog/WhatsApp%20Image%202026-06-14%20at%2010.19.39%20AM%20(3).jpeg', 'WhatsApp Image 2026-06-14 at 10.19.39 AM (3).jpeg', 55, false),
  ('baladi-chicken', 'Baladi Frozen Chicken', 'دجاج بلدي مجمد', 'No.1 baladi frozen whole chicken.', 'دجاج بلدي مجمد الرقم ١.', '1100g+ · Frozen · No.1', '١١٠٠ج+ · مجمد · الرقم ١', 42, 'Poultry', 'دواجن', 'https://otuewefcsusojkjfgadv.supabase.co/storage/v1/object/public/product-images/catalog/WhatsApp%20Image%202026-06-14%20at%2010.19.40%20AM.jpeg', 'WhatsApp Image 2026-06-14 at 10.19.40 AM.jpeg', 45, false),
  ('sunflower-17l', 'Soul Gold Sunflower Oil 17L', 'زيت صول الذهبية ١٧ لتر', 'Premium 17L tin of 100% pure sunflower oil.', 'عبوة فاخرة ١٧ لتر من زيت دوار الشمس الصافي.', '100% Pure · Premium Tin', 'صافي ١٠٠٪ · عبوة فاخرة', 95, 'Oils', 'زيوت', 'https://otuewefcsusojkjfgadv.supabase.co/storage/v1/object/public/product-images/catalog/WhatsApp%20Image%202026-06-14%20at%2011.06.56%20AM%20(1).jpeg', 'WhatsApp Image 2026-06-14 at 11.06.56 AM (1).jpeg', 40, true),
  ('fresh-chicken-sg', 'Soul Gold Fresh Chicken', 'دجاج صول الذهبية فريش', '100% natural fresh chicken, Saudi origin.', 'دجاج طازج طبيعي ١٠٠٪ من مصدر سعودي.', '100% Natural · Saudi Origin', '١٠٠٪ طبيعي · مصدر سعودي', 36, 'Poultry', 'دواجن', 'https://otuewefcsusojkjfgadv.supabase.co/storage/v1/object/public/product-images/catalog/WhatsApp%20Image%202026-06-14%20at%2011.06.56%20AM%20(2).jpeg', 'WhatsApp Image 2026-06-14 at 11.06.56 AM (2).jpeg', 65, true),
  ('fresh-fish', 'Soul Gold Fresh Fish', 'أسماك طازجة', 'Fresh daily premium fish cuts.', 'أسماك طازجة يومياً بقطع فاخرة.', 'Fresh Daily · Premium Cut', 'طازج يومياً · قطع فاخرة', 38, 'Seafood', 'مأكولات بحرية', 'https://otuewefcsusojkjfgadv.supabase.co/storage/v1/object/public/product-images/catalog/WhatsApp%20Image%202026-06-14%20at%2011.06.56%20AM%20(3).jpeg', 'WhatsApp Image 2026-06-14 at 11.06.56 AM (3).jpeg', 50, true),
  ('fresh-beef', 'Soul Gold Fresh Beef', 'لحم بقري طازج', '100% natural Saudi-made fresh beef.', 'لحم بقري طازج طبيعي ١٠٠٪ صناعة سعودية.', '100% Natural · Saudi Made', '١٠٠٪ طبيعي · منتج سعودي', 48, 'Meat', 'لحوم', 'https://otuewefcsusojkjfgadv.supabase.co/storage/v1/object/public/product-images/catalog/WhatsApp%20Image%202026-06-14%20at%2011.06.56%20AM%20(4).jpeg', 'WhatsApp Image 2026-06-14 at 11.06.56 AM (4).jpeg', 35, true),
  ('premium-eggs', 'Premium Table Eggs', 'بيض مائدة فاخر', '30 premium quality table eggs.', '٣٠ بيضة مائدة بجودة فاخرة.', '30 Eggs · Premium Quality', '٣٠ بيضة · جودة فاخرة', 32, 'Dairy', 'ألبان', 'https://otuewefcsusojkjfgadv.supabase.co/storage/v1/object/public/product-images/catalog/WhatsApp%20Image%202026-06-14%20at%2011.06.56%20AM%20(5).jpeg', 'WhatsApp Image 2026-06-14 at 11.06.56 AM (5).jpeg', 80, false),
  ('eggs-family-30', 'Premium Eggs Family Pack', 'بيض عائلي فاخر', 'Family pack of 30 premium table eggs.', 'عبوة عائلية من ٣٠ بيضة مائدة فاخرة.', 'Family Pack · 30 Eggs', 'عبوة عائلية · ٣٠ بيضة', 32, 'Dairy', 'ألبان', 'https://otuewefcsusojkjfgadv.supabase.co/storage/v1/object/public/product-images/catalog/WhatsApp%20Image%202026-06-14%20at%2011.06.56%20AM%20(6).jpeg', 'WhatsApp Image 2026-06-14 at 11.06.56 AM (6).jpeg', 70, true),
  ('chicken-feed', 'Premium Chicken Feed', 'أعلاف دجاج فاخرة', 'High-protein premium poultry feed.', 'أعلاف دجاج فاخرة غنية بالبروتين.', 'High Protein · Saudi Made', 'بروتين عالي · صناعة سعودية', 55, 'Supplies', 'مستلزمات', 'https://otuewefcsusojkjfgadv.supabase.co/storage/v1/object/public/product-images/catalog/WhatsApp%20Image%202026-06-14%20at%2011.06.56%20AM%20(7).jpeg', 'WhatsApp Image 2026-06-14 at 11.06.56 AM (7).jpeg', 30, false),
  ('mixed-veg-frozen', 'Frozen Mixed Vegetables', 'خضار مشكلة مجمدة', 'Premium green beans, peas and carrots. 100% natural, quickly frozen.', 'فاصوليا خضراء وبازلاء وجزر فاخر. طبيعي ١٠٠٪ ومجمد بسرعة.', 'Beans · Peas & Carrots · Quick Frozen', 'فاصوليا · بازلاء وجزر · مجمد سريع', 16, 'Frozen', 'مجمدات', 'https://otuewefcsusojkjfgadv.supabase.co/storage/v1/object/public/product-images/catalog/WhatsApp%20Image%202026-06-14%20at%2010.19.34%20AM.jpeg', 'WhatsApp Image 2026-06-14 at 10.19.34 AM.jpeg', 100, false),
  ('caramel-syrup', 'Natural Caramel Syrup', 'شراب كراميل طبيعي', 'Rich natural caramel syrup for desserts, coffee, and pancakes.', 'شراب كراميل طبيعي غني للحلويات والقهوة والفطائر.', 'Natural · Desserts & Drinks', 'طبيعي · حلويات ومشروبات', 24, 'Sauces', 'صلصات', 'https://otuewefcsusojkjfgadv.supabase.co/storage/v1/object/public/product-images/catalog/WhatsApp%20Image%202026-06-14%20at%2010.19.36%20AM.jpeg', 'WhatsApp Image 2026-06-14 at 10.19.36 AM.jpeg', 60, false),
  ('luxury-egyptian-rice', 'Luxury Egyptian Rice', 'أرز مصري فاخر', 'Premium long-grain Egyptian rice in a 5kg family pack.', 'أرز مصري طويل الحبة فاخر في عبوة عائلية ٥ كجم.', '5kg · Best Quality', '٥ كجم · أفضل جودة', 58, 'Grains', 'حبوب', 'https://otuewefcsusojkjfgadv.supabase.co/storage/v1/object/public/product-images/catalog/WhatsApp%20Image%202026-06-14%20at%2010.19.36%20AM%20(2).jpeg', 'WhatsApp Image 2026-06-14 at 10.19.36 AM (2).jpeg', 75, false),
  ('premium-tomato-sauce-4kg', 'Premium Tomato Sauce', 'صلصة طماطم فاخرة', '100% natural tomato sauce from selected farms. 4050g tin.', 'صلصة طماطم طبيعية ١٠٠٪ من أفضل المزارع. عبوة ٤٠٥٠ جرام.', '4050g · 100% Natural', '٤٠٥٠ج · طبيعي ١٠٠٪', 42, 'Sauces', 'صلصات', 'https://otuewefcsusojkjfgadv.supabase.co/storage/v1/object/public/product-images/catalog/WhatsApp%20Image%202026-06-14%20at%2010.19.38%20AM%20(1).jpeg', 'WhatsApp Image 2026-06-14 at 10.19.38 AM (1).jpeg', 55, true),
  ('premium-white-tuna', 'Premium White Tuna', 'تونة بيضاء فاخرة', 'Solid white tuna — excellent protein source. 80g and 160g sizes.', 'تونة بيضاء قطع صلبة — مصدر ممتاز للبروتين. ٨٠ و١٦٠ جرام.', '80g · 160g · Guaranteed Quality', '٨٠ج · ١٦٠ج · جودة مضمونة', 18, 'Canned', 'معلبات', 'https://otuewefcsusojkjfgadv.supabase.co/storage/v1/object/public/product-images/catalog/WhatsApp%20Image%202026-06-14%20at%2010.19.38%20AM.jpeg', 'WhatsApp Image 2026-06-14 at 10.19.38 AM.jpeg', 90, true),
  ('fresh-beef-vacuum', 'Fresh Beef — Vacuum Pack', 'لحم بقري طازج معبأ', '100% natural Saudi beef, vacuum-sealed and delivered fresh daily.', 'لحم بقري سعودي طبيعي ١٠٠٪، معبأ بالتفريغ ويوصل طازجاً يومياً.', '100% Natural · Fresh Daily', '١٠٠٪ طبيعي · طازج يومياً', 52, 'Meat', 'لحوم', 'https://otuewefcsusojkjfgadv.supabase.co/storage/v1/object/public/product-images/catalog/WhatsApp%20Image%202026-06-14%20at%2011.14.30%20AM%20(3).jpeg', 'WhatsApp Image 2026-06-14 at 11.14.30 AM (3).jpeg', 40, false)
ON CONFLICT (sku) DO UPDATE SET
  name_en          = EXCLUDED.name_en,
  name_ar          = EXCLUDED.name_ar,
  description_en   = EXCLUDED.description_en,
  description_ar   = EXCLUDED.description_ar,
  sub_en           = EXCLUDED.sub_en,
  sub_ar           = EXCLUDED.sub_ar,
  price            = EXCLUDED.price,
  category_en      = EXCLUDED.category_en,
  category_ar      = EXCLUDED.category_ar,
  image_url        = EXCLUDED.image_url,
  image_file       = EXCLUDED.image_file,
  stock_quantity   = EXCLUDED.stock_quantity,
  is_featured      = EXCLUDED.is_featured,
  updated_at       = NOW();
