-- ═══════════════════════════════════════════════════════════════════
-- Soul Gold — Full automated setup (idempotent, safe to re-run)
-- Executed by: npm run setup:supabase
-- ═══════════════════════════════════════════════════════════════════

-- ── Orders (checkout) ──────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.orders (
  id               UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  customer_name    TEXT NOT NULL,
  customer_phone   TEXT NOT NULL,
  customer_address TEXT NOT NULL,
  items            JSONB NOT NULL,
  total_price      NUMERIC(10,2) NOT NULL CHECK (total_price >= 0),
  created_at       TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "orders_public_insert" ON public.orders;
CREATE POLICY "orders_public_insert"
  ON public.orders FOR INSERT
  WITH CHECK (true);

-- ── Products v2 (Shopify-style catalog) ────────────────────────────
-- Drop legacy v1 schema (no sku column) so v2 can be created cleanly
DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public' AND table_name = 'products' AND column_name = 'category'
  ) AND NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public' AND table_name = 'products' AND column_name = 'sku'
  ) THEN
    DROP TABLE public.products CASCADE;
  END IF;
END $$;

CREATE TABLE IF NOT EXISTS public.products (
  id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sku              TEXT NOT NULL UNIQUE,
  name_en          TEXT NOT NULL,
  name_ar          TEXT NOT NULL,
  description_en   TEXT,
  description_ar   TEXT,
  sub_en           TEXT,
  sub_ar           TEXT,
  price            NUMERIC(10,2) NOT NULL CHECK (price >= 0),
  category_en      TEXT NOT NULL,
  category_ar      TEXT NOT NULL,
  image_url        TEXT NOT NULL,
  image_file       TEXT,
  stock_quantity   INTEGER NOT NULL DEFAULT 0 CHECK (stock_quantity >= 0),
  is_featured      BOOLEAN NOT NULL DEFAULT false,
  badge_en         TEXT,
  badge_ar         TEXT,
  bg_color         TEXT NOT NULL DEFAULT 'bg-cream',
  created_at       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at       TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE OR REPLACE FUNCTION public.set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS products_updated_at ON public.products;
CREATE TRIGGER products_updated_at
  BEFORE UPDATE ON public.products
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "products_public_read" ON public.products;
CREATE POLICY "products_public_read"
  ON public.products FOR SELECT
  USING (true);

CREATE INDEX IF NOT EXISTS products_category_en_idx ON public.products (category_en);
CREATE INDEX IF NOT EXISTS products_is_featured_idx ON public.products (is_featured);
CREATE INDEX IF NOT EXISTS products_sku_idx ON public.products (sku);

-- ── Storage buckets ────────────────────────────────────────────────
INSERT INTO storage.buckets (id, name, public)
VALUES ('product-images', 'product-images', true)
ON CONFLICT (id) DO UPDATE SET public = true;

INSERT INTO storage.buckets (id, name, public)
VALUES ('brand-assets', 'brand-assets', true)
ON CONFLICT (id) DO UPDATE SET public = true;

-- product-images policies
DROP POLICY IF EXISTS "product_images_public_read" ON storage.objects;
CREATE POLICY "product_images_public_read"
  ON storage.objects FOR SELECT
  USING (bucket_id = 'product-images');

DROP POLICY IF EXISTS "product_images_service_upload" ON storage.objects;
CREATE POLICY "product_images_service_upload"
  ON storage.objects FOR INSERT
  WITH CHECK (bucket_id = 'product-images');

DROP POLICY IF EXISTS "product_images_service_update" ON storage.objects;
CREATE POLICY "product_images_service_update"
  ON storage.objects FOR UPDATE
  USING (bucket_id = 'product-images');

DROP POLICY IF EXISTS "product_images_service_delete" ON storage.objects;
CREATE POLICY "product_images_service_delete"
  ON storage.objects FOR DELETE
  USING (bucket_id = 'product-images');

-- brand-assets policies
DROP POLICY IF EXISTS "brand_assets_public_read" ON storage.objects;
CREATE POLICY "brand_assets_public_read"
  ON storage.objects FOR SELECT
  USING (bucket_id = 'brand-assets');

DROP POLICY IF EXISTS "brand_assets_service_upload" ON storage.objects;
CREATE POLICY "brand_assets_service_upload"
  ON storage.objects FOR INSERT
  WITH CHECK (bucket_id = 'brand-assets');

DROP POLICY IF EXISTS "brand_assets_service_update" ON storage.objects;
CREATE POLICY "brand_assets_service_update"
  ON storage.objects FOR UPDATE
  USING (bucket_id = 'brand-assets');

DROP POLICY IF EXISTS "brand_assets_service_delete" ON storage.objects;
CREATE POLICY "brand_assets_service_delete"
  ON storage.objects FOR DELETE
  USING (bucket_id = 'brand-assets');
