-- Citrus Foodstuff Trading — fresh produce seed data
-- Run this entire script in the Supabase SQL Editor (Dashboard → SQL → New query).
-- WARNING: This deletes ALL existing rows in public.products before inserting new data.

BEGIN;

DELETE FROM public.products;

-- Reset identity sequence so new IDs start at 1 (optional but keeps IDs tidy)
ALTER SEQUENCE IF EXISTS public.products_id_seq RESTART WITH 1;

INSERT INTO public.products (
  sku, name_en, name_ar, description_en, description_ar,
  sub_en, sub_ar, price, category_en, category_ar,
  image_url, image_file, stock_quantity, is_featured,
  badge_en, badge_ar
) VALUES

-- Fresh Fruits
(
  'chaunsa-mango',
  'Chaunsa Mango',
  'مانجو تشونسا',
  'Export-quality Pakistani Chaunsa mangoes — exceptionally sweet, juicy, and handpicked from Punjab orchards.',
  'مانجو تشونسا باكستاني بجودة تصدير — حلو جداً وعصيري ومحصود يدوياً من بساتين البنجاب.',
  '5Kg',
  '٥ كجم',
  89.00,
  'Fresh Fruits',
  'فواكه طازجة',
  'https://images.unsplash.com/photo-1553277197-99508c49d374?w=800&q=80',
  'chaunsa-mango.jpg',
  120,
  true,
  'HOT',
  'الأكثر مبيعاً'
),
(
  'fresh-indian-banana',
  'Fresh Indian Banana',
  'موز هندي طازج',
  'Naturally sweet Indian bananas — rich in potassium, perfect for breakfast, smoothies, and daily snacking.',
  'موز هندي طبيعي حلو — غني بالبوتاسيوم، مثالي للفطور والعصائر والوجبات اليومية.',
  'Kg',
  'كجم',
  12.50,
  'Fresh Fruits',
  'فواكه طازجة',
  'https://images.unsplash.com/photo-1571771894821-ce9b6bdc11d9?w=800&q=80',
  'indian-banana.jpg',
  200,
  false,
  NULL,
  NULL
),
(
  'fresh-oranges-navel',
  'Fresh Navel Oranges',
  'برتقال طازج',
  'Juicy navel oranges packed with vitamin C — ideal for juicing or fresh eating.',
  'برتقال عصيري غني بفيتامين C — مثالي للعصير أو التناول الطازج.',
  '10Kg',
  '١٠ كجم',
  39.99,
  'Fresh Fruits',
  'فواكه طازجة',
  'https://images.unsplash.com/photo-1547513567-1217a9c77a0b?w=800&q=80',
  'navel-oranges.jpg',
  85,
  false,
  NULL,
  NULL
),
(
  'green-apples',
  'Green Apples',
  'تفاح أخضر',
  'Crisp, tart green apples — perfect for salads, baking, and healthy snacking.',
  'تفاح أخضر مقرمش — مثالي للسلطات والخبز والوجبات الصحية.',
  '18Kg',
  '١٨ كجم',
  45.00,
  'Fresh Fruits',
  'فواكه طازجة',
  'https://images.unsplash.com/photo-1560806887-1ff4b63fd2bc?w=800&q=80',
  'green-apples.jpg',
  70,
  false,
  NULL,
  NULL
),
(
  'pomegranate-india',
  'Pomegranate India',
  'رمان هندي',
  'Ruby-red Indian pomegranates with sweet-tart arils — antioxidant-rich and refreshing.',
  'رمان هندي أحمر غني بمضادات الأكسدة — حلو لاذع ومنعش.',
  '2Kg',
  '٢ كجم',
  28.00,
  'Fresh Fruits',
  'فواكه طازجة',
  'https://images.unsplash.com/photo-1615485850319-bad69a34a3ec?w=800&q=80',
  'pomegranate.jpg',
  60,
  false,
  NULL,
  NULL
),
(
  'fresh-strawberries',
  'Fresh Strawberries',
  'فراولة طازجة',
  'Plump, fragrant strawberries — hand-selected for sweetness and vibrant color.',
  'فراولة طازجة عطرية — مختارة يدوياً لحلاوتها ولونها الزاهي.',
  '500g',
  '٥٠٠ ج',
  22.00,
  'Fresh Fruits',
  'فواكه طازجة',
  'https://images.unsplash.com/photo-1464960914005-9b743b284972?w=800&q=80',
  'strawberries.jpg',
  90,
  false,
  'NEW',
  'جديد'
),
(
  'jamun-java-plum',
  'Jamun (Java Plum)',
  'جامون (توت أسود)',
  'Deep purple tropical Jamun — sweet-tangy flavor loaded with antioxidants and vitamin C.',
  'جامون استوائي أرجواني — طعم حلو لاذع غني بمضادات الأكسدة وفيتامين C.',
  'Kg',
  'كجم',
  34.00,
  'Fresh Fruits',
  'فواكه طازجة',
  'https://images.unsplash.com/photo-1592924353639-1e0529d7b9a1?w=800&q=80',
  'jamun.jpg',
  45,
  false,
  NULL,
  NULL
),
(
  'watermelon-seedless',
  'Seedless Watermelon',
  'بطيخ بدون بذور',
  'Large seedless watermelon — ultra-hydrating and perfect for summer gatherings.',
  'بطيخ كبير بدون بذور — منعش ومثالي لجمعات الصيف.',
  'Whole',
  'حبة',
  18.00,
  'Fresh Fruits',
  'فواكه طازجة',
  'https://images.unsplash.com/photo-15631147738684-6c0f13141081?w=800&q=80',
  'watermelon.jpg',
  55,
  false,
  NULL,
  NULL
),

-- Fresh Vegetables
(
  'organic-tomatoes',
  'Organic Tomatoes',
  'طماطم عضوية',
  'Vine-ripened organic tomatoes — firm, flavorful, and perfect for salads and cooking.',
  'طماطم عضوية ناضجة على الكرمة — متماسكة ولذيذة للسلطات والطبخ.',
  'Kg',
  'كجم',
  14.00,
  'Fresh Vegetables',
  'خضروات طازجة',
  'https://images.unsplash.com/photo-1546094096-0df4bcaaa337?w=800&q=80',
  'organic-tomatoes.jpg',
  150,
  true,
  NULL,
  NULL
),
(
  'hass-avocado',
  'Hass Avocado',
  'أفوكادو هاس',
  'Creamy Hass avocados — rich in healthy fats, ideal for guacamole, toast, and salads.',
  'أفوكادو هاس كريمي — غني بالدهون الصحية، مثالي للجوacamole والسلطات.',
  '4 Pieces',
  '٤ حبات',
  24.00,
  'Fresh Vegetables',
  'خضروات طازجة',
  'https://images.unsplash.com/photo-1523049673857-eb18f1fade7a?w=800&q=80',
  'hass-avocado.jpg',
  110,
  true,
  'NEW',
  'جديد'
),
(
  'red-onions-india',
  'Red Onions India',
  'بصل أحمر هندي',
  'Sharp, aromatic red onions — essential for curries, salads, and everyday cooking.',
  'بصل أحمر هندي عطري — أساسي للكاري والسلطات والطبخ اليومي.',
  'Kg',
  'كجم',
  8.50,
  'Fresh Vegetables',
  'خضروات طازجة',
  'https://images.unsplash.com/photo-1518977676601-b53f82aba655?w=800&q=80',
  'red-onions.jpg',
  180,
  false,
  NULL,
  NULL
),
(
  'fresh-broccoli',
  'Fresh Broccoli',
  'بروكلي طازج',
  'Nutrient-dense broccoli crowns — crisp, green, and packed with vitamins.',
  'بروكلي طازج غني بالعناصر — مقرمش وأخضر ومليء بالفيتامينات.',
  'Kg',
  'كجم',
  16.00,
  'Fresh Vegetables',
  'خضروات طازجة',
  'https://images.unsplash.com/photo-1459411553490-7b66f7c5683a?w=800&q=80',
  'broccoli.jpg',
  95,
  false,
  NULL,
  NULL
),
(
  'baby-carrots',
  'Baby Carrots',
  'جزر صغير',
  'Sweet, tender baby carrots — ready to eat, perfect for lunchboxes and crudité platters.',
  'جزر صغير حلو وطري — جاهز للأكل، مثالي للوجبات الخفيفة.',
  '500g',
  '٥٠٠ ج',
  9.00,
  'Fresh Vegetables',
  'خضروات طازجة',
  'https://images.unsplash.com/photo-1598170847810-1d0e5d09e41f?w=800&q=80',
  'baby-carrots.jpg',
  130,
  false,
  NULL,
  NULL
),
(
  'english-cucumber',
  'English Cucumber',
  'خيار إنجليزي',
  'Long, seedless English cucumbers — cool, crisp, and ideal for salads and tzatziki.',
  'خيار إنجليزي طويل بدون بذور — منعش ومثالي للسلطات.',
  'Kg',
  'كجم',
  11.00,
  'Fresh Vegetables',
  'خضروات طازجة',
  'https://images.unsplash.com/photo-1449307427810-7c47ce0e7c7c?w=800&q=80',
  'cucumber.jpg',
  100,
  false,
  NULL,
  NULL
),
(
  'mixed-bell-peppers',
  'Mixed Bell Peppers',
  'فلفل ملون مشكل',
  'Colorful mix of red, yellow, and green bell peppers — sweet and crunchy.',
  'مزيج من الفلفل الأحمر والأصفر والأخضر — حلو ومقرمش.',
  'Kg',
  'كجم',
  19.00,
  'Fresh Vegetables',
  'خضروات طازجة',
  'https://images.unsplash.com/photo-1563567735213-9a60275d9d6f?w=800&q=80',
  'bell-peppers.jpg',
  75,
  false,
  NULL,
  NULL
),
(
  'aubergine-fresh',
  'Fresh Aubergine',
  'باذنجان طازج',
  'Glossy purple aubergines — meaty texture perfect for grilling, roasting, and curries.',
  'باذنجان أرجواني لامع — قوام لحمي مثالي للشوي والكاري.',
  '20Kg',
  '٢٠ كجم',
  32.00,
  'Fresh Vegetables',
  'خضروات طازجة',
  'https://images.unsplash.com/photo-1627387343193-f080ada8b128?w=800&q=80',
  'aubergine.jpg',
  65,
  false,
  NULL,
  NULL
),

-- Leaf's & Herbs
(
  'fresh-basil-bunch',
  'Fresh Basil Bunch',
  'ريحان طازج',
  'Fragrant basil bunch — essential for Italian dishes, pesto, and fresh garnishes.',
  'ريحان طازج عطري — أساسي للأطباق الإيطالية والبستو.',
  'Bunch',
  'حزمة',
  6.50,
  'Leaf''s & Herbs',
  'أوراق وأعشاب',
  'https://images.unsplash.com/photo-1618375582378-8950b6f88e83?w=800&q=80',
  'basil.jpg',
  80,
  false,
  NULL,
  NULL
),
(
  'fresh-mint-bunch',
  'Fresh Mint Bunch',
  'نعناع طازج',
  'Cool, aromatic mint — perfect for tea, salads, and Middle Eastern cuisine.',
  'نعناع طازج منعش — مثالي للشاي والسلطات والمطبخ العربي.',
  'Bunch',
  'حزمة',
  5.00,
  'Leaf''s & Herbs',
  'أوراق وأعشاب',
  'https://images.unsplash.com/photo-1416879595882-3373a0480b05?w=800&q=80',
  'mint.jpg',
  90,
  false,
  NULL,
  NULL
),

-- Local
(
  'emirati-khalas-dates',
  'Emirati Khalas Dates',
  'تمر خلاص إماراتي',
  'Premium UAE Khalas dates — naturally sweet, soft, and traditionally harvested.',
  'تمر خلاص إماراتي فاخر — حلو طبيعياً وطري ومحصود تقليدياً.',
  '1Kg',
  '١ كجم',
  55.00,
  'Local',
  'محلي',
  'https://images.unsplash.com/photo-1595853035660-f205460ce9e7?w=800&q=80',
  'khalas-dates.jpg',
  50,
  true,
  NULL,
  NULL
),

-- Gift Basket
(
  'royal-fruit-basket',
  'Royal Fruit Basket',
  'سلة فواكه ملكية',
  'Luxury assorted fruit basket — mangoes, grapes, berries, and seasonal premium picks.',
  'سلة فواكه فاخرة مشكلة — مانجو وعنب وتوت وفواكه موسمية مميزة.',
  'Gift Box',
  'صندوق هدايا',
  149.00,
  'Gift Basket',
  'سلة هدايا',
  'https://images.unsplash.com/photo-1619563690155-fe99c5c32660?w=800&q=80',
  'royal-fruit-basket.jpg',
  40,
  true,
  'HOT',
  'الأكثر مبيعاً'
),
(
  'premium-citrus-gift-hamper',
  'Premium Citrus Gift Hamper',
  'سلة هدايا حمضيات فاخرة',
  'Elegant hamper of oranges, lemons, grapefruits, and exotic citrus — perfect corporate gift.',
  'سلة أنيقة من البرتقال والليمون والجريب فروت — هدية مثالية للشركات.',
  'Hamper',
  'سلة',
  199.00,
  'Gift Basket',
  'سلة هدايا',
  'https://images.unsplash.com/photo-1563245372-63f309543482?w=800&q=80',
  'citrus-hamper.jpg',
  25,
  true,
  NULL,
  NULL
),

-- Bulk Order
(
  'bulk-potatoes-20kg',
  'Bulk Potatoes (20Kg)',
  'بطاطس بالجملة (٢٠ كجم)',
  'Washed bulk potatoes — ideal for restaurants, catering, and large households.',
  'بطاطس مغسولة بالجملة — مثالية للمطاعم والتموين والعائلات الكبيرة.',
  '20Kg',
  '٢٠ كجم',
  38.00,
  'Bulk Order',
  'طلب بالجملة',
  'https://images.unsplash.com/photo-1506399529667-68e55f7b3233?w=800&q=80',
  'bulk-potatoes.jpg',
  200,
  false,
  NULL,
  NULL
),
(
  'bulk-onions-25kg',
  'Bulk White Onions (25Kg)',
  'بصل أبيض بالجملة (٢٥ كجم)',
  'Restaurant-grade white onions in bulk sack — consistent quality for high-volume kitchens.',
  'بصل أبيض بجودة مطاعم في كيس بالجملة — جودة ثابتة للمطابخ الكبيرة.',
  '25Kg',
  '٢٥ كجم',
  42.00,
  'Bulk Order',
  'طلب بالجملة',
  'https://images.unsplash.com/photo-1618375582378-8950b6f88e83?w=800&q=80',
  'bulk-onions.jpg',
  150,
  false,
  NULL,
  NULL
),
(
  'elephant-yam-suran',
  'Elephant Yam (Suran)',
  'يام فيل (سوران)',
  'Fresh elephant yam — starchy root vegetable popular in South Asian and UAE cuisines.',
  'يام فيل طازج — خضار جذرية نشوية شائعة في المطبخ الآسيوي والإماراتي.',
  'Kg',
  'كجم',
  15.00,
  'Local',
  'محلي',
  'https://images.unsplash.com/photo-1598170847810-1d0e5d09e41f?w=800&q=80',
  'elephant-yam.jpg',
  70,
  false,
  NULL,
  NULL
);

COMMIT;

-- Verify: SELECT count(*), category_en FROM public.products GROUP BY category_en ORDER BY category_en;
