-- ═══════════════════════════════════════════════════════════════════
-- Soul Gold — Products Schema v2 (Shopify-style catalog)
-- Run this in Supabase SQL Editor AFTER backing up existing data.
-- ═══════════════════════════════════════════════════════════════════

-- Drop legacy table if migrating fresh (comment out if you have live orders referencing product ids)
-- DROP TABLE IF EXISTS public.products CASCADE;

CREATE TABLE IF NOT EXISTS public.products (
  id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sku              TEXT NOT NULL UNIQUE,
  name_en          TEXT NOT NULL,
  name_ar          TEXT NOT NULL,
  description_en   TEXT,
  description_ar   TEXT,
  sub_en           TEXT,
  sub_ar           TEXT,
  price            NUMERIC(10,2) NOT NULL CHECK (price >= 0),
  category_en      TEXT NOT NULL,
  category_ar      TEXT NOT NULL,
  image_url        TEXT NOT NULL,
  image_file       TEXT,
  stock_quantity   INTEGER NOT NULL DEFAULT 0 CHECK (stock_quantity >= 0),
  is_featured      BOOLEAN NOT NULL DEFAULT false,
  badge_en         TEXT,
  badge_ar         TEXT,
  bg_color         TEXT NOT NULL DEFAULT 'bg-cream',
  created_at       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at       TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Auto-update updated_at
CREATE OR REPLACE FUNCTION public.set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS products_updated_at ON public.products;
CREATE TRIGGER products_updated_at
  BEFORE UPDATE ON public.products
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- Row Level Security
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "products_public_read" ON public.products;
CREATE POLICY "products_public_read"
  ON public.products FOR SELECT
  USING (true);

-- Index for common queries
CREATE INDEX IF NOT EXISTS products_category_en_idx ON public.products (category_en);
CREATE INDEX IF NOT EXISTS products_is_featured_idx ON public.products (is_featured);
CREATE INDEX IF NOT EXISTS products_sku_idx ON public.products (sku);

-- ═══════════════════════════════════════════════════════════════════
-- Supabase Storage bucket for product images
-- (Also create via Dashboard → Storage → New bucket: "product-images", Public)
-- ═══════════════════════════════════════════════════════════════════

INSERT INTO storage.buckets (id, name, public)
VALUES ('product-images', 'product-images', true)
ON CONFLICT (id) DO NOTHING;

DROP POLICY IF EXISTS "product_images_public_read" ON storage.objects;
CREATE POLICY "product_images_public_read"
  ON storage.objects FOR SELECT
  USING (bucket_id = 'product-images');

-- Allow service role / authenticated uploads (migration script uses service role key)
DROP POLICY IF EXISTS "product_images_service_upload" ON storage.objects;
CREATE POLICY "product_images_service_upload"
  ON storage.objects FOR INSERT
  WITH CHECK (bucket_id = 'product-images');

DROP POLICY IF EXISTS "product_images_service_update" ON storage.objects;
CREATE POLICY "product_images_service_update"
  ON storage.objects FOR UPDATE
  USING (bucket_id = 'product-images');

-- NOTE: Product rows are seeded via:
--   npm run setup:supabase
-- which runs supabase/setup-all.sql, uploads assets, and seeds from data/products.seed.json.
